name: Deploy to production

on:
  workflow_dispatch:

jobs:
  quarto:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      GIT_AUTH_TOKEN: ${{ secrets.GH_PAT }}
      
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: git checkout -B prod

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Install curl
        run: |
          sudo apt -y install libcurl4-openssl-dev

      - name: Cache R packages"
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R Packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.56

      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2

      - name: Remove last 4 lines from .gitignore
        run: |
          head -n -4 .gitignore > temp && mv temp .gitignore
          rm -f temp

      - name: Minify .css
        uses: nizarmah/auto-minify@v3
        with:
          overwrite: true
          directory: "css"

      - name: Minify .js
        uses: nizarmah/auto-minify@v3
        with:
          overwrite: true
          directory: "js"

      - name: Remove unnecessary files
        run: |
          rm -f web.Rproj
          rm -f web.code-workspace
          rm -f renv.lock
          rm -f .Rprofile
          rm -f .rooignore
          rm -f _quarto.yml
          rm -rf renv/
          find . -name "*.qmd" -type f -delete

      - name: Set timestamp
        id: set_timestamp
        run: |
          echo 'timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S")' >> $GITHUB_OUTPUT

      - name: Commit all changes to prod (single commit)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Prodification - ${{ steps.set_timestamp.outputs.timestamp }}"
          branch: prod
          push_options: '--force'
